### PR TITLE
added body-row-2

### PR DESCRIPTION
**Pull request by Khqled-syr**

### CODE REVIEW

**Comment by Nefn-Lakhouj** [comment]
hi @Levaii i see ther is a problem with( Run npm run lint:ls) can you check that please?

**Comment by Levaii** [comment]
Hey @Nefn-Lakhouj
I already ran that and I'm not getting any errors!!

**Comment by Nefn-Lakhouj** [comment]
i check that can you change the name of photo to (body-row-2) and put this (image) on html it will be worked @Levaii

**Comment by Nefn-Lakhouj** [comment]
@Levaii it's done i fix it i will merge that

**Comment by Khqled-syr** [comment]
@Nefn-Lakhouj cool thank you!

**Pull request merged**
